/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

export interface Rule {
	/** List of rule IDs this rule is dependent on. */
	dependent_rules: string[];
	/** The end line of the rule in the source code. */
	end_line: number;
	/** The ID of the rule. */
	rule_id: string;
	/** The start line of the rule in the source code. */
	start_line: number;
}
