/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

export type RuleChildElseAllOfType =
	(typeof RuleChildElseAllOfType)[keyof typeof RuleChildElseAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleChildElseAllOfType = {
	child: "child",
} as const;
