/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

export type RuleChildAllOfType =
	(typeof RuleChildAllOfType)[keyof typeof RuleChildAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleChildAllOfType = {
	child: "child",
} as const;
