/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */
import type { RuleParentAllOfChildrenItem } from "./ruleParentAllOfChildrenItem";
import type { RuleParentAllOfType } from "./ruleParentAllOfType";

export type RuleParentAllOf = {
	children?: RuleParentAllOfChildrenItem[];
	default?: string;
	type?: RuleParentAllOfType;
};
