/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */
import type { RuleChild } from "./ruleChild";
import type { RuleChildElseAllOfType } from "./ruleChildElseAllOfType";
import type { RuleParent } from "./ruleParent";

export type RuleChildElseAllOf = {
	children: RuleChild[];
	else: boolean;
	parent: RuleParent;
	type: RuleChildElseAllOfType;
};
