/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

export interface Sample {
	/** The content of the sample file. */
	content: string;
	/** The name of the sample file. */
	file_name: string;
}
