/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

/**
 * List of default inputs for the sample.
 */
export type SampleDefaultInputs = {
	default: string;
	[key: string]: string;
};
