// Code generated by ogen, DO NOT EDIT.

package api

type AstGetOK struct {
	// The generated AST.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *AstGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *AstGetOK) SetResult(val string) {
	s.Result = val
}

type DepTreeTextGetOK struct {
	// The generated dependency tree.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *DepTreeTextGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *DepTreeTextGetOK) SetResult(val string) {
	s.Result = val
}

type FlowchartGetOK struct {
	// The generated flowchart mermaid url.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *FlowchartGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *FlowchartGetOK) SetResult(val string) {
	s.Result = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Rule
type Rule struct {
	// The ID of the rule.
	RuleID string `json:"rule_id"`
	// List of rule IDs this rule is dependent on.
	DependentRules []string `json:"dependent_rules"`
	// The start line of the rule in the source code.
	StartLine int32 `json:"start_line"`
	// The end line of the rule in the source code.
	EndLine int32 `json:"end_line"`
}

// GetRuleID returns the value of RuleID.
func (s *Rule) GetRuleID() string {
	return s.RuleID
}

// GetDependentRules returns the value of DependentRules.
func (s *Rule) GetDependentRules() []string {
	return s.DependentRules
}

// GetStartLine returns the value of StartLine.
func (s *Rule) GetStartLine() int32 {
	return s.StartLine
}

// GetEndLine returns the value of EndLine.
func (s *Rule) GetEndLine() int32 {
	return s.EndLine
}

// SetRuleID sets the value of RuleID.
func (s *Rule) SetRuleID(val string) {
	s.RuleID = val
}

// SetDependentRules sets the value of DependentRules.
func (s *Rule) SetDependentRules(val []string) {
	s.DependentRules = val
}

// SetStartLine sets the value of StartLine.
func (s *Rule) SetStartLine(val int32) {
	s.StartLine = val
}

// SetEndLine sets the value of EndLine.
func (s *Rule) SetEndLine(val int32) {
	s.EndLine = val
}

// Ref: #/components/schemas/Sample
type Sample struct {
	// The name of the sample file.
	FileName string `json:"file_name"`
	// The content of the sample file.
	Content string `json:"content"`
}

// GetFileName returns the value of FileName.
func (s *Sample) GetFileName() string {
	return s.FileName
}

// GetContent returns the value of Content.
func (s *Sample) GetContent() string {
	return s.Content
}

// SetFileName sets the value of FileName.
func (s *Sample) SetFileName(val string) {
	s.FileName = val
}

// SetContent sets the value of Content.
func (s *Sample) SetContent(val string) {
	s.Content = val
}

type VarTracePostOK struct {
	// The output of variable trace.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *VarTracePostOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *VarTracePostOK) SetResult(val string) {
	s.Result = val
}
