// Code generated by ogen, DO NOT EDIT.

package api

type AstGetOK struct {
	// The generated AST.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *AstGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *AstGetOK) SetResult(val string) {
	s.Result = val
}

type DepTreeTextGetOK struct {
	// The generated dependency tree.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *DepTreeTextGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *DepTreeTextGetOK) SetResult(val string) {
	s.Result = val
}

type FlowchartGetOK struct {
	// The generated flowchart mermaid url.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *FlowchartGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *FlowchartGetOK) SetResult(val string) {
	s.Result = val
}

// Ref: #/components/schemas/Rule
type Rule struct {
	// The ID of the rule.
	RuleID string `json:"rule_id"`
	// List of rule IDs this rule is dependent on.
	DependentRules []string `json:"dependent_rules"`
	// The start line of the rule in the source code.
	StartLine int32 `json:"start_line"`
	// The end line of the rule in the source code.
	EndLine int32 `json:"end_line"`
}

// GetRuleID returns the value of RuleID.
func (s *Rule) GetRuleID() string {
	return s.RuleID
}

// GetDependentRules returns the value of DependentRules.
func (s *Rule) GetDependentRules() []string {
	return s.DependentRules
}

// GetStartLine returns the value of StartLine.
func (s *Rule) GetStartLine() int32 {
	return s.StartLine
}

// GetEndLine returns the value of EndLine.
func (s *Rule) GetEndLine() int32 {
	return s.EndLine
}

// SetRuleID sets the value of RuleID.
func (s *Rule) SetRuleID(val string) {
	s.RuleID = val
}

// SetDependentRules sets the value of DependentRules.
func (s *Rule) SetDependentRules(val []string) {
	s.DependentRules = val
}

// SetStartLine sets the value of StartLine.
func (s *Rule) SetStartLine(val int32) {
	s.StartLine = val
}

// SetEndLine sets the value of EndLine.
func (s *Rule) SetEndLine(val int32) {
	s.EndLine = val
}

// Ref: #/components/schemas/Sample
type Sample struct {
	// The name of the sample file.
	FileName string `json:"file_name"`
	// The content of the sample file.
	Content string `json:"content"`
}

// GetFileName returns the value of FileName.
func (s *Sample) GetFileName() string {
	return s.FileName
}

// GetContent returns the value of Content.
func (s *Sample) GetContent() string {
	return s.Content
}

// SetFileName sets the value of FileName.
func (s *Sample) SetFileName(val string) {
	s.FileName = val
}

// SetContent sets the value of Content.
func (s *Sample) SetContent(val string) {
	s.Content = val
}

type VarTracePostOK struct {
	// The output of variable trace.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *VarTracePostOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *VarTracePostOK) SetResult(val string) {
	s.Result = val
}
