/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

export interface EvalStep {
	index: number;
	message: string;
	targetNodeUid: string;
}
