import type { EvalStep } from "./evalStep";
/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */
import type { RuleParent } from "./ruleParent";

export type GetCallTree200 = {
	entrypoint: RuleParent;
	steps?: EvalStep[];
};
