/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */
import type { NodeBase } from "./nodeBase";
import type { RuleStatementAllOf } from "./ruleStatementAllOf";

export type RuleStatement = NodeBase & RuleStatementAllOf;
