/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

export type RuleParentAllOfType =
	(typeof RuleParentAllOfType)[keyof typeof RuleParentAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleParentAllOfType = {
	parent: "parent",
} as const;
