/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */
import type { RuleChild } from "./ruleChild";
import type { RuleChildElse } from "./ruleChildElse";

export type RuleParentAllOfChildrenItem = RuleChild | RuleChildElse;
