/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * regoviz
 * api for regoviz
 * OpenAPI spec version: 1.0.0
 */

/**
 * List of query examples for the sample.
 */
export type SampleQueryExamples = {
	/** The default query for the sample. Can be empty. */
	default: string;
	[key: string]: string;
};
