/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Title
 * Title
 * OpenAPI spec version: 1.0.0
 */
export type GetAst200 = {
	/** The generated AST */
	result?: string;
};

export type GetAstParams = {
	/**
	 * The module string to analyze
	 */
	module: string;
};

export type GetDepTreeText200 = {
	/** The generated dependency tree */
	result?: string;
};

export type GetDepTreeTextParams = {
	/**
	 * The module string to analyze
	 */
	module: string;
};

export interface Sample {
	/** The content of the sample file. */
	content?: string;
	/** The name of the sample file. */
	file_name?: string;
}

export interface Rule {
	/** List of rule IDs this rule is dependent on. */
	dependent_rules?: string[];
	/** The end line of the rule in the source code. */
	end_line?: number;
	/** The ID of the rule. */
	rule_id?: string;
	/** The start line of the rule in the source code. */
	start_line?: number;
}
