// Code generated by ogen, DO NOT EDIT.

package api

type AstGetOK struct {
	// The generated AST.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *AstGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *AstGetOK) SetResult(val string) {
	s.Result = val
}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type DepTreeTextGetOK struct {
	// The generated dependency tree.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *DepTreeTextGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *DepTreeTextGetOK) SetResult(val string) {
	s.Result = val
}

type FlowchartGetOK struct {
	// The generated flowchart mermaid url.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *FlowchartGetOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *FlowchartGetOK) SetResult(val string) {
	s.Result = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Rule
type Rule struct {
	// The ID of the rule.
	RuleID string `json:"rule_id"`
	// List of rule IDs this rule is dependent on.
	DependentRules []string `json:"dependent_rules"`
	// The start line of the rule in the source code.
	StartLine int32 `json:"start_line"`
	// The end line of the rule in the source code.
	EndLine int32 `json:"end_line"`
}

// GetRuleID returns the value of RuleID.
func (s *Rule) GetRuleID() string {
	return s.RuleID
}

// GetDependentRules returns the value of DependentRules.
func (s *Rule) GetDependentRules() []string {
	return s.DependentRules
}

// GetStartLine returns the value of StartLine.
func (s *Rule) GetStartLine() int32 {
	return s.StartLine
}

// GetEndLine returns the value of EndLine.
func (s *Rule) GetEndLine() int32 {
	return s.EndLine
}

// SetRuleID sets the value of RuleID.
func (s *Rule) SetRuleID(val string) {
	s.RuleID = val
}

// SetDependentRules sets the value of DependentRules.
func (s *Rule) SetDependentRules(val []string) {
	s.DependentRules = val
}

// SetStartLine sets the value of StartLine.
func (s *Rule) SetStartLine(val int32) {
	s.StartLine = val
}

// SetEndLine sets the value of EndLine.
func (s *Rule) SetEndLine(val int32) {
	s.EndLine = val
}

// Ref: #/components/schemas/Sample
type Sample struct {
	// The name of the sample file.
	FileName string `json:"file_name"`
	// The content of the sample file.
	Content string `json:"content"`
	// List of default inputs for the sample.
	DefaultInputs SampleDefaultInputs `json:"default_inputs"`
	// List of default data for the sample.
	DefaultData SampleDefaultData `json:"default_data"`
	// List of default queries for the sample.
	DefaultQueries SampleDefaultQueries `json:"default_queries"`
}

// GetFileName returns the value of FileName.
func (s *Sample) GetFileName() string {
	return s.FileName
}

// GetContent returns the value of Content.
func (s *Sample) GetContent() string {
	return s.Content
}

// GetDefaultInputs returns the value of DefaultInputs.
func (s *Sample) GetDefaultInputs() SampleDefaultInputs {
	return s.DefaultInputs
}

// GetDefaultData returns the value of DefaultData.
func (s *Sample) GetDefaultData() SampleDefaultData {
	return s.DefaultData
}

// GetDefaultQueries returns the value of DefaultQueries.
func (s *Sample) GetDefaultQueries() SampleDefaultQueries {
	return s.DefaultQueries
}

// SetFileName sets the value of FileName.
func (s *Sample) SetFileName(val string) {
	s.FileName = val
}

// SetContent sets the value of Content.
func (s *Sample) SetContent(val string) {
	s.Content = val
}

// SetDefaultInputs sets the value of DefaultInputs.
func (s *Sample) SetDefaultInputs(val SampleDefaultInputs) {
	s.DefaultInputs = val
}

// SetDefaultData sets the value of DefaultData.
func (s *Sample) SetDefaultData(val SampleDefaultData) {
	s.DefaultData = val
}

// SetDefaultQueries sets the value of DefaultQueries.
func (s *Sample) SetDefaultQueries(val SampleDefaultQueries) {
	s.DefaultQueries = val
}

// List of default data for the sample.
type SampleDefaultData struct {
	Default         string `json:"default"`
	AdditionalProps SampleDefaultDataAdditional
}

// GetDefault returns the value of Default.
func (s *SampleDefaultData) GetDefault() string {
	return s.Default
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *SampleDefaultData) GetAdditionalProps() SampleDefaultDataAdditional {
	return s.AdditionalProps
}

// SetDefault sets the value of Default.
func (s *SampleDefaultData) SetDefault(val string) {
	s.Default = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *SampleDefaultData) SetAdditionalProps(val SampleDefaultDataAdditional) {
	s.AdditionalProps = val
}

type SampleDefaultDataAdditional map[string]string

func (s *SampleDefaultDataAdditional) init() SampleDefaultDataAdditional {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// List of default inputs for the sample.
type SampleDefaultInputs struct {
	Default         string `json:"default"`
	AdditionalProps SampleDefaultInputsAdditional
}

// GetDefault returns the value of Default.
func (s *SampleDefaultInputs) GetDefault() string {
	return s.Default
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *SampleDefaultInputs) GetAdditionalProps() SampleDefaultInputsAdditional {
	return s.AdditionalProps
}

// SetDefault sets the value of Default.
func (s *SampleDefaultInputs) SetDefault(val string) {
	s.Default = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *SampleDefaultInputs) SetAdditionalProps(val SampleDefaultInputsAdditional) {
	s.AdditionalProps = val
}

type SampleDefaultInputsAdditional map[string]string

func (s *SampleDefaultInputsAdditional) init() SampleDefaultInputsAdditional {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// List of default queries for the sample.
type SampleDefaultQueries struct {
	Default         string `json:"default"`
	AdditionalProps SampleDefaultQueriesAdditional
}

// GetDefault returns the value of Default.
func (s *SampleDefaultQueries) GetDefault() string {
	return s.Default
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *SampleDefaultQueries) GetAdditionalProps() SampleDefaultQueriesAdditional {
	return s.AdditionalProps
}

// SetDefault sets the value of Default.
func (s *SampleDefaultQueries) SetDefault(val string) {
	s.Default = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *SampleDefaultQueries) SetAdditionalProps(val SampleDefaultQueriesAdditional) {
	s.AdditionalProps = val
}

type SampleDefaultQueriesAdditional map[string]string

func (s *SampleDefaultQueriesAdditional) init() SampleDefaultQueriesAdditional {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type VarTracePostOK struct {
	// The output of variable trace.
	Result string `json:"result"`
}

// GetResult returns the value of Result.
func (s *VarTracePostOK) GetResult() string {
	return s.Result
}

// SetResult sets the value of Result.
func (s *VarTracePostOK) SetResult(val string) {
	s.Result = val
}
